# Generated by Django 4.1.5 on 2023-01-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cnab_transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cnabtransactions",
            old_name="store_owner",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="cnabtransactions",
            old_name="store_name",
            new_name="store",
        ),
    ]
